import { AUTH_DOMAINS_ENV_KEY } from "alchemy-utils/auth-deploy-hostnames";
import type { EnvRequirement } from "alchemy-utils/env-requirements";

export const AUTH_WORKER_ENV_REQUIREMENTS: readonly EnvRequirement[] = [
	{
		key: "BETTER_AUTH_SECRET",
		setupCategory: "core-secrets",
		kind: "secret",
		requiredIn: ["local", "staging", "prod"],
		githubSync: "required",
		title: "Better Auth secret",
		description: "Signing secret for Better Auth sessions and tokens",
		canAutoGenerate: true,
	},
	{
		key: "AUTH_ADMIN_SECRET",
		setupCategory: "core-secrets",
		kind: "secret",
		requiredIn: ["local", "staging", "prod"],
		githubSync: "required",
		title: "Auth admin API secret",
		description: "Machine access to auth worker admin API (trusted origins)",
		canAutoGenerate: true,
	},
	{
		key: "AUTH_BOOTSTRAP_ADMIN_EMAILS",
		setupCategory: "core-secrets",
		kind: "variable",
		requiredIn: ["local", "staging", "prod"],
		githubSync: "optional",
		title: "Bootstrap admin emails",
		description: "Comma-separated emails granted admin role on first login",
		plaintextInSetup: true,
	},
	{
		key: AUTH_DOMAINS_ENV_KEY,
		setupCategory: "custom-domains",
		kind: "variable",
		requiredIn: [],
		optionalSetupModes: ["staging", "prod"],
		githubSync: "optional",
		title: "Auth worker custom domains",
		description:
			"Optional dedicated auth host (e.g. auth.example.com) · otherwise auth URL is derived from WEB_DOMAINS or web workers.dev",
		plaintextInSetup: true,
	},
	{
		key: "GOOGLE_CLIENT_ID",
		setupCategory: "core-secrets",
		kind: "variable",
		requiredIn: [],
		optionalSetupModes: ["local", "staging", "prod"],
		githubSync: "optional",
		title: "Google OAuth client ID",
		description: "OAuth 2.0 client ID from Google Cloud Console",
		plaintextInSetup: true,
	},
	{
		key: "GOOGLE_CLIENT_SECRET",
		setupCategory: "core-secrets",
		kind: "secret",
		requiredIn: [],
		optionalSetupModes: ["local", "staging", "prod"],
		githubSync: "optional",
		title: "Google OAuth client secret",
		description: "OAuth 2.0 client secret from Google Cloud Console",
		canAutoGenerate: false,
	},
	{
		key: "GITHUB_CLIENT_ID",
		setupCategory: "core-secrets",
		kind: "variable",
		requiredIn: [],
		optionalSetupModes: ["local", "staging", "prod"],
		githubSync: "optional",
		title: "GitHub OAuth client ID",
		description: "OAuth App client ID from GitHub",
		plaintextInSetup: true,
	},
	{
		key: "GITHUB_CLIENT_SECRET",
		setupCategory: "core-secrets",
		kind: "secret",
		requiredIn: [],
		optionalSetupModes: ["local", "staging", "prod"],
		githubSync: "optional",
		title: "GitHub OAuth client secret",
		description: "OAuth App client secret from GitHub",
		canAutoGenerate: false,
	},
];
